export const GET_USERS_DATA = "GET_USERS_DATA";
export const SET_USERS_DATA = "SET_USERS_DATA";
export const HANDLE_DELETE_MODAL_VISIBILITY = "HANDLE_DELETE_MODAL_VISIBILITY";
export const DELETE_USER = "DELETE_USER";
export const HANDLE_ADD_MODAL_VISIBILITY = "HANDLE_ADD_MODAL_VISIBILITY";
export const ADD_USER = "ADD_USER";
export const HANDLE_UPDATE_MODAL_VISIBILITY = "HANDLE_UPDATE_MODAL_VISIBILITY";
export const UPDATE_USER = "UPDATE_USER";
